#Pandas (panel data analysis):

- panel data analysis : Excel(Rows and Columns)
- 1.pandas series
  - one dimensional : single column
  - its a single column holding data of any type
- 2.pandas dataframe
  - More than one dimensions(2D)

#To instal any libraries:
- step1 : pip install library_name
- step2 : import library_name
- step3 : To call any library using this keyword import

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
print(dir(pd))

['ArrowDtype', 'BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_built_with_meson', '_config', '_is_numpy_dev', '_libs', '_pandas_datetime_CAPI', '_pandas_parser_CAPI', '_testing', '_typing', '_version_meson', 'annotations', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'concat', 'core', 'crosstab', 'cut', 'date_range', 'describe_option', 'errors', 'eval', 'factorize', 'from_dummies', 'get_dummies', 'get_option', 'infer_freq', 'interval_range', 'io', 'isna', 'isnull', 'json_normalize', 'lreshape', 'melt', 'merge', 'merge_asof', 'merge_ordered', 'notna', 'notnull', 'offsets', 'option_context', 'options', 'pandas', 'period_range', 'pivot', 'pivot_table', 'plotting', 'qcut', 'read_clipboard', 'read_csv', 'read_excel', 'read_feather', 'read_fwf', 'read_gbq', 'read_hdf', 'read_html', 'read_json', 'read_orc', 'read_parquet', 'read_pickle', 'read_sas', 'read_spss', 'read_sql', 'read_sql_query', 'read_sql_table', 'read_stata', 'read_table', 'read_xml', 'reset_option', 'set_eng_float_format', 'set_option', 'show_versions', 'test', 'testing', 'timedelta_range', 'to_datetime', 'to_numeric', 'to_pickle', 'to_timedelta', 'tseries', 'unique', 'util', 'value_counts', 'wide_to_long']

In [ ]:
pd.__version__

'2.2.2'

In [ ]:
import numpy as np

In [ ]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array_repr', 'array_split', 'array_str', 'asanyarray', 'asarray', 'asarray_chkfinite', 'ascontiguousarray', 'asfortranarray', 'asin', 'asinh', 'asmatrix', 'astype', 'atan', 'atan2', 'atanh', 'atleast_1d', 'atleast_2d', 'atleast_3d', 'average', 'bartlett', 'base_repr', 'binary_repr', 'bincount', 'bitwise_and', 'bitwise_count', 'bitwise_invert', 'bitwise_left_shift', 'bitwise_not', 'bitwise_or', 'bitwise_right_shift', 'bitwise_xor', 'blackman', 'block', 'bmat', 'bool', 'bool_', 'broadcast', 'broadcast_arrays', 'broadcast_shapes', 'broadcast_to', 'busday_count', 'busday_offset', 'busdaycalendar', 'byte', 'bytes_', 'c_', 'can_cast', 'cbrt', 'cdouble', 'ceil', 'char', 'character', 'choose', 'clip', 'clongdouble', 'column_stack', 'common_type', 'complex128', 'complex256', 'complex64', 'complexfloating', 'compress', 'concat', 'concatenate', 'conj', 'conjugate', 'convolve', 'copy', 'copysign', 'copyto', 'core', 'corrcoef', 'correlate', 'cos', 'cosh', 'count_nonzero', 'cov', 'cross', 'csingle', 'ctypeslib', 'cumprod', 'cumsum', 'datetime64', 'datetime_as_string', 'datetime_data', 'deg2rad', 'degrees', 'delete', 'diag', 'diag_indices', 'diag_indices_from', 'diagflat', 'diagonal', 'diff', 'digitize', 'divide', 'divmod', 'dot', 'double', 'dsplit', 'dstack', 'dtype', 'dtypes', 'e', 'ediff1d', 'einsum', 'einsum_path', 'emath', 'empty', 'empty_like', 'equal', 'errstate', 'euler_gamma', 'exceptions', 'exp', 'exp2', 'expand_dims', 'expm1', 'expm1x', 'extract', 'eye', 'f2py', 'fabs', 'fft', 'fill_diagonal', 'finfo', 'fix', 'flatiter', 'flatnonzero', 'flexible', 'flip', 'fliplr', 'flipud', 'float128', 'float16', 'float32', 'float64', 'float_power', 'floating', 'floor', 'floor_divide', 'fmax', 'fmin', 'fmod', 'format_float_positional', 'format_float_scientific', 'frexp', 'from_dlpack', 'frombuffer', 'fromfile', 'fromfunction', 'fromiter', 'frompyfunc', 'fromregex', 'fromstring', 'full', 'full_like', 'gcd', 'generic', 'genfromtxt', 'geomspace', 'get_include', 'get_printoptions', 'getbufsize', 'geterr', 'geterrcall', 'gradient', 'greater', 'greater_equal', 'half', 'hamming', 'hanning', 'heaviside', 'histogram', 'histogram2d', 'histogram_bin_edges', 'histogramdd', 'hsplit', 'hstack', 'hypot', 'i0', 'identity', 'iinfo', 'imag', 'in1d', 'index_exp', 'indices', 'inexact', 'inf', 'info', 'inner', 'insert', 'int16', 'int32', 'int64', 'int8', 'int_', 'intc', 'integer', 'interp', 'intersect1d', 'intp', 'invert', 'is_busday', 'isclose', 'iscomplex', 'iscomplexobj', 'isdtype', 'isfinite', 'isfortran', 'isin', 'isinf', 'isnan', 'isnat', 'isneginf', 'isposinf', 'isreal', 'isrealobj', 'isscalar', 'issubdtype', 'iterable', 'ix_', 'kaiser', 'kron', 'lcm', 'ldexp', 'left_shift', 'less', 'less_equal', 'lexsort', 'lib', 'linalg', 'linspace', 'little_endian', 'load', 'loadtxt', 'log', 'log10', 'log1p', 'log2', 'logaddexp', 'logaddexp2', 'logical_and', 'logical_not', 'logical_or', 'logical_xor', 'logspace', 'long', 'longdouble', 'longlong', 'ma', 'mask_indices', 'matmul', 'matrix', 'matrix_transpose', 'max', 'maximum', 'may_share_memory', 'mean', 'median', 'memmap', 'meshgrid', 'mgrid', 'min', 'min_scalar_type', 'minimum', 'mintypecode', 'mod', 'modf', 'moveaxis', 'multiply', 'nan', 'nan_to_num', 'nanargmax', 'nanargmin', 'nancumprod', 'nancumsum', 'nanmax', 'nanmean', 'nanmedian', 'nanmin', 'nanpercentile', 'nanprod', 'nanquantile', 'nanstd', 'nansum', 'nanvar', 'ndarray', 'ndenumerate', 'ndim', 'ndindex', 'nditer', 'negative', 'nested_iters', 'newaxis', 'nextafter', 'nonzero', 'not_equal', 'number', 'object_', 'ogrid', 'ones', 'ones_like', 'outer', 'packbits', 'pad', 'partition', 'percentile', 'permute_dims', 'pi', 'piecewise', 'place', 'poly', 'poly1d', 'polyadd', 'polyder', 'polydiv', 'polyfit', 'polyint', 'polymul', 'polynomial', 'polysub', 'polyval', 'positive', 'pow', 'power', 'printoptions', 'prod', 'promote_types', 'ptp', 'put', 'put_along_axis', 'putmask', 'quantile', 'r_', 'rad2deg', 'radians', 'random', 'ravel', 'ravel_multi_index', 'real', 'real_if_close', 'rec', 'recarray', 'reciprocal', 'record', 'remainder', 'repeat', 'require', 'reshape', 'resize', 'result_type', 'right_shift', 'rint', 'roll', 'rollaxis', 'roots', 'rot90', 'round', 'row_stack', 's_', 'save', 'savetxt', 'savez', 'savez_compressed', 'sctypeDict', 'searchsorted', 'select', 'set_printoptions', 'setbufsize', 'setdiff1d', 'seterr', 'seterrcall', 'setxor1d', 'shape', 'shares_memory', 'short', 'show_config', 'show_runtime', 'sign', 'signbit', 'signedinteger', 'sin', 'sinc', 'single', 'sinh', 'size', 'sort', 'sort_complex', 'spacing', 'split', 'sqrt', 'square', 'squeeze', 'stack', 'std', 'str_', 'strings', 'subtract', 'sum', 'swapaxes', 'take', 'take_along_axis', 'tan', 'tanh', 'tensordot', 'test', 'testing', 'tile', 'timedelta64', 'trace', 'transpose', 'trapezoid', 'trapz', 'tri', 'tril', 'tril_indices', 'tril_indices_from', 'trim_zeros', 'triu', 'triu_indices', 'triu_indices_from', 'true_divide', 'trunc', 'typecodes', 'typename', 'typing', 'ubyte', 'ufunc', 'uint', 'uint16', 'uint32', 'uint64', 'uint8', 'uintc', 'uintp', 'ulong', 'ulonglong', 'union1d', 'unique', 'unique_all', 'unique_counts', 'unique_inverse', 'unique_values', 'unpackbits', 'unravel_index', 'unsignedinteger', 'unwrap', 'ushort', 'vander', 'var', 'vdot', 'vecdot', 'vectorize', 'void', 'vsplit', 'vstack', 'where', 'zeros', 'zeros_like']

##Creating series using list,tuple,dictionary

In [ ]:
#creating empty series
data=pd.Series()
data

Series([], dtype: object)

In [ ]:
l=[1,2,3]
print(type(l))

<class 'list'>

In [ ]:
type(data)

pandas.core.series.Series

####creating series using list

In [ ]:
data2=pd.Series(l)
data2
# by default index : 0,1,2,3,......

0    1
1    2
2    3
dtype: int64

####creating series using Tuple

In [ ]:
data3=pd.Series((1,2,3,4,"affan",4.6,[4,5,6],True,{6,7},(1,2,3)))
data3

0            1
1            2
2            3
3            4
4        affan
5          4.6
6    [4, 5, 6]
7         True
8       {6, 7}
9    (1, 2, 3)
dtype: object

####Parameters/Attributes:
- syntax:
  - Series(seq,index,name)

In [ ]:
data2

0    1
1    2
2    3
dtype: int64

In [ ]:
data4=pd.Series([1,2,3],index=["a","b","c"],name="numbers")
data4

a    1
b    2
c    3
Name: numbers, dtype: int64

####creating series using dictionary

In [ ]:
d={"name":"affan","age":22,"city":"Baramati"}
data5=pd.Series(d)
data5

name       affan
age           22
city    Baramati
dtype: object

In [ ]:
# Don't need of index using Dictionary
d={"name":"affan","age":22,"city":"Baramati"}
data5=pd.Series(d,index=[1,2,3])
data5

1    NaN
2    NaN
3    NaN
dtype: object

In [ ]:
d={"name":"affan","age":22,"city":"Baramati"}
data5=pd.Series(d,name="dictionary")
data5

name       affan
age           22
city    Baramati
Name: dictionary, dtype: object

####dtype

In [ ]:
l=[1,2,3,4]
s1=pd.Series(l,dtype=float)
s1

0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64

In [ ]:
l1=[1,2,3,4]
s1=pd.Series(l1,dtype=str)
s1

0    1
1    2
2    3
3    4
dtype: object

####Attributes

In [ ]:
s1.dtype

dtype('float64')

In [ ]:
data5.name

'dictionary'

In [ ]:
s1.shape
# shape=(row,columns)

(4,)

In [ ]:
data4.index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
s1.values

array([1., 2., 3., 4.])

In [ ]:
s1.size

4

In [ ]:
s1.ndim
# show the dimension

1

In [ ]:
s1.is_unique

True

In [ ]:
s1.empty

False

In [ ]:
data.empty

True

In [ ]:
s1.hasnans

False

In [ ]:
# To implement nan value you need numpy library and "np.nan" function
# employees
employees=pd.Series({"name":"affan","city":np.nan,"salary":4567})
employees

name      affan
city        NaN
salary     4567
dtype: object

In [ ]:
employees.hasnans

True

#Series Function:

In [ ]:
#Arithmatic function

In [ ]:
import pandas as pd

In [ ]:
s1=pd.Series([1,2,3,4])
s2=pd.Series([10,20,30,40,50,60])

In [ ]:
#int<float<str

In [ ]:
s1

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
s2

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [ ]:
s1.mean()  # Average

np.float64(2.5)

In [ ]:
s1.median() # Middle Value

2.5

In [ ]:
s2.mean()  # Average

np.float64(35.0)

In [ ]:
s2.median()  #Middle Value

35.0

In [ ]:
s1.min()

1

In [ ]:
s1.max()

4

In [ ]:
s2.min()

10

In [ ]:
s2.max()

60

In [ ]:
import statistics as st

In [ ]:
print(dir(st))

['Counter', 'Decimal', 'Fraction', 'LinearRegression', 'NormalDist', 'StatisticsError', '_SQRT2', '__all__', '__annotations__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_coerce', '_convert', '_decimal_sqrt_of_frac', '_exact_ratio', '_fail_neg', '_float_sqrt_of_frac', '_integer_sqrt_of_frac_rto', '_isfinite', '_mean_stdev', '_normal_dist_inv_cdf', '_rank', '_sqrt_bit_width', '_ss', '_sum', 'bisect_left', 'bisect_right', 'correlation', 'count', 'covariance', 'defaultdict', 'erf', 'exp', 'fabs', 'fmean', 'fsum', 'geometric_mean', 'groupby', 'harmonic_mean', 'hypot', 'itemgetter', 'linear_regression', 'log', 'math', 'mean', 'median', 'median_grouped', 'median_high', 'median_low', 'mode', 'multimode', 'namedtuple', 'numbers', 'pstdev', 'pvariance', 'quantiles', 'random', 'reduce', 'repeat', 'sqrt', 'stdev', 'sumprod', 'sys', 'tau', 'variance']

In [ ]:
# If series contains Text Data the Arithmetic doesnt work
l3=[2,4,2,5,4.5,6,"a","b"]
s3=pd.Series(l3)
s3

0      2
1      4
2      2
3      5
4    4.5
5      6
6      a
7      b
dtype: object

In [ ]:
s3.mean()

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [ ]:
s3.median()

TypeError: could not convert string to float: 'a'

In [ ]:
s3.min()

TypeError: '<=' not supported between instances of 'int' and 'str'

In [ ]:
# std : standard deviation
s2.std()

18.708286933869708

In [ ]:
# var : variance()
s2.var()

350.0

In [ ]:
# describe : provide all statistics of the data
s2.describe()

count     6.000000
mean     35.000000
std      18.708287
min      10.000000
25%      22.500000
50%      35.000000
75%      47.500000
max      60.000000
dtype: float64

#Data Cleaning Fns:
- 1.drop() : parameter pass : index
- 2.replace() : parameter : (old text , new text)
- 3.isnull() : check value null or not : true and false answer
- 4.fillna() : TO fill null values
- 5.append() : in recent version like 2.3.3 append method is deprecated
- 6.sort_values() : sort by value
- 7.sort_index() : sort by index
- 8.unique()     : show only distinct values
- 9.value_counts() : count of numbers
- 10.nunique() : count of unique numbers
- 11.loc() : label based slicing
- 12.iloc() : index based slicing

In [ ]:
s1=pd.Series([1,2,3,4],index=["a","b","c","d"])
s1

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
# This function don't run becoz i don't download current version
s1.drop("b")
s1

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
# This function don't run becoz i don't download current version
# replace
s1.replace(1,10)
s1

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
s1.isnull()

a    False
b    False
c    False
d    False
dtype: bool

In [ ]:
s1.fillna()

ValueError: Must specify a fill 'value' or 'method'.

In [ ]:
import pandas as pd

In [ ]:
list1=[7,3,52,1,0,7,3,2]
se1=pd.Series(list1)
se1

0     7
1     3
2    52
3     1
4     0
5     7
6     3
7     2
dtype: int64

In [ ]:
se1.sort_values()

4     0
3     1
7     2
1     3
6     3
0     7
5     7
2    52
dtype: int64

#Slicing in series :

In [ ]:
s1=pd.Series([1,2,3,4],index=["a","b","c","d"])
s1

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
s1["a":"d"]

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
s1["a":"d":2]

a    1
c    3
dtype: int64

####loc(): label based work
####iloc() : index based work

In [ ]:
s1.iloc[2]

np.int64(3)

In [ ]:
import pandas as pd
l=[1,2,3,1,2,34]
new_series=pd.Series(l)
new_series

0     1
1     2
2     3
3     1
4     2
5    34
dtype: int64

In [ ]:
# extract 34 using iloc
new_series.iloc[5]

0     affan
1    tanmay
2     vijay
3     sahil
4      aman
dtype: object

#Series Arithmatic Operations:

###Difference Between List and Series:
- List - Hetroginious ==> Multiple Data Type
  - l1=[1,2.3,"Affan"]
  - l2=["Tanmay",20,30]
  - For Arithmetic Operations Between Two List we need Lopp's
- Series - Homoginious ==> Single Data Type
  - s=[1,2,3.5,"Affan",7.8.9]==> ["1","2","3.5","Affan","7.8","9"]
  - prefernces
    - str>float>int
  - Arithmetic operators ==> faster ==> due to same data types
  - There is no need of loops for Arithmetic opeartions
  - larger data

In [ ]:
l1=[45,1,2.3]
l2=[20,30,45]
l1+l2

# indexwise Addition

print(l1[0]+l2[0])
print(l1[1]+l2[1])
print(l1[2]+l2[2])

65
31
47.3

In [ ]:
# Using For loop
l1=[45,1,2.3]
l2=[20,30,45]
l1+l2
addition=[]
for i in range(len(l1)):
  addition.append(l1[i]+l2[i])
print(addition)

[65, 31, 47.3]

In [ ]:
import pandas as pd
import numpy as np
s1=pd.Series([1,2,3,4])
s2=pd.Series([10,20,30,40,np.nan,60,np.nan,80],index=[1,2,3,4,5,6,7,8])
s3=pd.Series([1,"Affan",45.6])

In [ ]:
s1

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
s2

1    10.0
2    20.0
3    30.0
4    40.0
5     NaN
6    60.0
7     NaN
8    80.0
dtype: float64

In [ ]:
s3

0        1
1    Affan
2     45.6
dtype: object

####Addition:

In [ ]:
# "+"
s1+s2  # index wise

0     NaN
1    12.0
2    23.0
3    34.0
4     NaN
5     NaN
6     NaN
7     NaN
8     NaN
dtype: float64

In [ ]:
# "+"
s1.add(s2)

0     NaN
1    12.0
2    23.0
3    34.0
4     NaN
5     NaN
6     NaN
7     NaN
8     NaN
dtype: float64

In [ ]:
# Don't Add because in s3 there are str
s1+s2+s3

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [ ]:
s1.dtype

dtype('int64')

In [ ]:
s2.dtype

dtype('float64')

In [ ]:
s3.dtype

dtype('O')

####Substraction:

In [ ]:
# index wise arithmetic operations works
s1-s2

0     NaN
1    -8.0
2   -17.0
3   -26.0
4     NaN
5     NaN
6     NaN
7     NaN
8     NaN
dtype: float64

In [ ]:
s1.sub(s2)

0     NaN
1    -8.0
2   -17.0
3   -26.0
4     NaN
5     NaN
6     NaN
7     NaN
8     NaN
dtype: float64

####Multiplication:

In [ ]:
s1*s2

0      NaN
1     20.0
2     60.0
3    120.0
4      NaN
5      NaN
6      NaN
7      NaN
8      NaN
dtype: float64

In [ ]:
s1.mul(s2)

0      NaN
1     20.0
2     60.0
3    120.0
4      NaN
5      NaN
6      NaN
7      NaN
8      NaN
dtype: float64

####Division:

In [ ]:
s1/s2

0         NaN
1    0.200000
2    0.150000
3    0.133333
4         NaN
5         NaN
6         NaN
7         NaN
8         NaN
dtype: float64

In [ ]:
s1.div(s2)

0         NaN
1    0.200000
2    0.150000
3    0.133333
4         NaN
5         NaN
6         NaN
7         NaN
8         NaN
dtype: float64

####floordivision:

In [ ]:
s1//s2

0    NaN
1    0.0
2    0.0
3    0.0
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
dtype: float64

In [ ]:
s1.floordiv(s2)

0    NaN
1    0.0
2    0.0
3    0.0
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
dtype: float64

####Modulus:

In [ ]:
s1%s2

0    NaN
1    2.0
2    3.0
3    4.0
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
dtype: float64

In [ ]:
s1.mod(s2)

0    NaN
1    2.0
2    3.0
3    4.0
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
dtype: float64

####power():

In [ ]:
s1**s2

0    1.000000e+00
1    1.024000e+03
2    3.486784e+09
3    1.152922e+18
4             NaN
5             NaN
6             NaN
7             NaN
8             NaN
dtype: float64

In [ ]:
s1.pow(s2)

0    1.000000e+00
1    1.024000e+03
2    3.486784e+09
3    1.152922e+18
4             NaN
5             NaN
6             NaN
7             NaN
8             NaN
dtype: float64

In [ ]:
s4=pd.Series([1,2,3],index=["A","B","C"])
s4

A    1
B    2
C    3
dtype: int64

In [ ]:
s1+s4

0   NaN
1   NaN
2   NaN
3   NaN
A   NaN
B   NaN
C   NaN
dtype: float64