#DataFrame:
- 1. Two Dimension Array holding data of any type
- 2. rows and Columns

Creating DataFrame using list,tuple,dict

In [ ]:
data=[1,2,3,4] # 1 dimension
data2=[[1,2,3,4],[5,6,7]] # 2 dimension

In [ ]:
import pandas as pd
s1=pd.Series(data)
s1

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
s2=pd.Series(data2)
s2

0    [1, 2, 3, 4]
1       [5, 6, 7]
dtype: object

Using List :

In [ ]:
df=pd.DataFrame(data)
df

   0
0  1
1  2
2  3
3  4

In [ ]:
df=pd.DataFrame(data2)
df

   0  1  2    3
0  1  2  3  4.0
1  5  6  7  NaN

In [ ]:
df=pd.DataFrame(data2,columns=["A","B","C","D"])
df

   A  B  C    D
0  1  2  3  4.0
1  5  6  7  NaN

In [ ]:
df1=pd.DataFrame(data,columns=["numbers"])
df1

   numbers
0        1
1        2
2        3
3        4

Using Tuple :

In [ ]:
t=("Affan","Tanmay",23,45)
s1=pd.Series(t)
s1

0     Affan
1    Tanmay
2        23
3        45
dtype: object

In [ ]:
df1=pd.DataFrame(t)
df1

        0
0   Affan
1  Tanmay
2      23
3      45

In [ ]:
t=(("Affan","Tanmay",23,45),("Affan","Tanmay",23))
s=pd.Series(t)
s

0    (Affan, Tanmay, 23, 45)
1        (Affan, Tanmay, 23)
dtype: object

In [ ]:
df1=pd.DataFrame(t,columns=["A","B","C","D"])
df1

       A       B   C     D
0  Affan  Tanmay  23  45.0
1  Affan  Tanmay  23   NaN

List of Tuples :

In [ ]:
t=[("Virat",4567),("Rohit",6756),("Hardik",3456)]
s=pd.Series(t)
s

0     (Virat, 4567)
1     (Rohit, 6756)
2    (Hardik, 3456)
dtype: object

In [ ]:
df1=pd.DataFrame(t)
df1

        0     1
0   Virat  4567
1   Rohit  6756
2  Hardik  3456

In [ ]:
df1=pd.DataFrame(t,columns=["Name","Runs"])
df1

     Name  Runs
0   Virat  4567
1   Rohit  6756
2  Hardik  3456

Using Dictionaries:

In [ ]:
cricketers_data={"name":["Virat","Rohit","Hardik"],"Runs":[3455,6546,7868]}
df1=pd.DataFrame(cricketers_data)
df1

     name  Runs
0   Virat  3455
1   Rohit  6546
2  Hardik  7868

Task:

In [ ]:
# Student data as a list of lists
students_list = [[101, "AFFAN", 85],[102, "TANMAY", 92],[103, "VIJAY", 78]]
df_students_list = pd.DataFrame(students_list, columns=["stdid", "name", "marks"])
display(df_students_list)

   stdid    name  marks
0    101   AFFAN     85
1    102  TANMAY     92
2    103   VIJAY     78

In [ ]:
# Student data as a dictionary
students_dict = {"stdid": [201, 202, 203],"name": ["Affan", "Tanmay", "Vijay"],"marks": [70, 95, 88]}
df_students_dict = pd.DataFrame(students_dict)
display(df_students_dict)

   stdid    name  marks
0    201   Affan     70
1    202  Tanmay     95
2    203   Vijay     88

In [ ]:
# using user (List)
s=[]
no_of_students=int(input("Enter number of students :"))
for i in range(no_of_students+1):
    stdid=int(input("Enter student id :"))
    name=input("Enter student name :")
    marks=float(input("Enter student marks :"))
    s.append([stdid,name,marks])
df=pd.DataFrame(s,columns=["stdid","name","marks"])
df

Enter number of students :2
Enter student id :101
Enter student name :AFFAN
Enter student marks :87
Enter student id :102
Enter student name :TANMAY
Enter student marks :67
Enter student id :103
Enter student name :VIJAY
Enter student marks :87

   stdid    name  marks
0    101   AFFAN   87.0
1    102  TANMAY   67.0
2    103   VIJAY   87.0

#Attributes of DataFrame :

In [ ]:
df1

     name  Runs
0   Virat  3455
1   Rohit  6546
2  Hardik  7868

In [ ]:
df1.shape

(3, 2)

In [ ]:
df1.name

0     Virat
1     Rohit
2    Hardik
Name: name, dtype: object

In [ ]:
df1.dtypes

name    object
Runs     int64
dtype: object

In [ ]:
df1.ndim

2

In [ ]:
df1.values

array([['Virat', 3455],
       ['Rohit', 6546],
       ['Hardik', 7868]], dtype=object)

In [ ]:
df1.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
df1.empty

False

In [ ]:
df1.index

RangeIndex(start=0, stop=3, step=1)

#Functions:

In [ ]:
df1["Runs"].sum()

np.int64(17869)

In [ ]:
df1["Runs"].mean()

np.float64(5956.333333333333)

In [ ]:
df1["Runs"].median()

6546.0

In [ ]:
df1["Runs"].min()

3455

In [ ]:
df1["Runs"].max()

7868

In [ ]:
df1["Runs"].std()

2264.822803959138

In [ ]:
df1["Runs"].var()

5129422.333333333

In [ ]:
df1["Runs"].describe()

count       3.000000
mean     5956.333333
std      2264.822804
min      3455.000000
25%      5000.500000
50%      6546.000000
75%      7207.000000
max      7868.000000
Name: Runs, dtype: float64

#How to Analsis Excel file using libraries :

In [ ]:
# if reading file if error occurs the error is
# Error
# if file extension is .xls
# you need to instal
# ---- pip install xlrd

In [ ]:
import pandas as pd
whether_data=pd.read_excel("/content/whether_data.xls")

In [ ]:
whether_data

          day  temperature  windspeed   event
0  2017-01-01         32.0        6.0    Rain
1  2017-01-04          NaN        7.0   Sunny
2  2017-01-05         28.0        NaN    Snow
3  2017-01-06          NaN        7.0     NaN
4  2017-01-07         32.0        NaN    Rain
5  2017-01-08         31.0        2.0   Sunny
6  2017-01-09          NaN        NaN     NaN
7  2017-01-10         34.0        8.0  Cloudy
8  2017-01-11         40.0       12.0     NaN
9  2017-01-10         34.0        8.0  Cloudy
10 2017-01-11         40.0       12.0     NaN

#EDA : Exploratory Data Analysis

####Step 1:
- we need to understand the data set
- no.of(rows and columns) ==> shape ==> (rows,columns)
- sample first 5 rows : head() : first 5 row show
- head(10) : first 10 row
- sample last 5 row : tail() : last 5 rows show
- tail(10) : last 10 row
- random any rows : sample() : 5 rows and sample(10)
- value counts

In [ ]:
whether_data.shape

(11, 4)

In [ ]:
whether_data.dtypes

day            datetime64[ns]
temperature           float64
windspeed             float64
event                  object
dtype: object

In [ ]:
whether_data.head()

         day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-04          NaN        7.0  Sunny
2 2017-01-05         28.0        NaN   Snow
3 2017-01-06          NaN        7.0    NaN
4 2017-01-07         32.0        NaN   Rain

In [ ]:
whether_data.head(10)

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        7.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08         31.0        2.0   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0     NaN
9 2017-01-10         34.0        8.0  Cloudy

In [ ]:
whether_data.tail()

          day  temperature  windspeed   event
6  2017-01-09          NaN        NaN     NaN
7  2017-01-10         34.0        8.0  Cloudy
8  2017-01-11         40.0       12.0     NaN
9  2017-01-10         34.0        8.0  Cloudy
10 2017-01-11         40.0       12.0     NaN

In [ ]:
whether_data.tail(2)

          day  temperature  windspeed   event
9  2017-01-10         34.0        8.0  Cloudy
10 2017-01-11         40.0       12.0     NaN

In [ ]:
whether_data.sample() # random any 1

         day  temperature  windspeed  event
5 2017-01-08         31.0        2.0  Sunny

In [ ]:
whether_data.sample(5) # random any 5

         day  temperature  windspeed   event
2 2017-01-05         28.0        NaN    Snow
5 2017-01-08         31.0        2.0   Sunny
4 2017-01-07         32.0        NaN    Rain
8 2017-01-11         40.0       12.0     NaN
7 2017-01-10         34.0        8.0  Cloudy

In [ ]:
whether_data.describe() # only numeric,datetime data statistics shows

                                 day  temperature  windspeed
count                             11     8.000000    8.00000
mean   2017-01-07 10:54:32.727272704    33.875000    7.75000
min              2017-01-01 00:00:00    28.000000    2.00000
25%              2017-01-05 12:00:00    31.750000    6.75000
50%              2017-01-08 00:00:00    33.000000    7.50000
75%              2017-01-10 00:00:00    35.500000    9.00000
max              2017-01-11 00:00:00    40.000000   12.00000
std                              NaN     4.223658    3.24037

In [ ]:
whether_data.info()
#datatype
#range,no of rows
#no of columns
#column names : non-null entry count : dtype
#dtype
#memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          11 non-null     datetime64[ns]
 1   temperature  8 non-null      float64
 2   windspeed    8 non-null      float64
 3   event        7 non-null      object
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 484.0+ bytes

In [ ]:
# column attributes
whether_data.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [ ]:
# value count
whether_data["event"].value_counts()

event
Rain      2
Sunny     2
Cloudy    2
Snow      1
Name: count, dtype: int64

####step 2: Data Cleaning
- Handling Missing Values ==> isnull() ==> check if null is present or not (True and False)
  - Total missing values ==> isnull().sum()
  - To fill Missing Values ==> fillna()
  - To drop Missing Values ==> dropna()
- Remove Duplicates
  - To check Duplicates rows ==> duplicated()
  - To drop Duplicates ==> drop_duplicates()
- Column names validation
  - total salary ==> total_salary
  - rename("old text","new text")
- Fix Data Types
  - astype() ==> covert the data types
- Handle Outliers
  - using filtering or statistical methods to remove outliers
- Handle Wrong(inconsistent) Data
  - replace(),drop()
- sorting
  - sort_values()
  - sort_values(ascending=True) ==> Descending sorting

In [ ]:
whether_data.isnull()

      day  temperature  windspeed  event
0   False        False      False  False
1   False         True      False  False
2   False        False       True  False
3   False         True      False   True
4   False        False       True  False
5   False        False      False  False
6   False         True       True   True
7   False        False      False  False
8   False        False      False   True
9   False        False      False  False
10  False        False      False   True

In [ ]:
whether_data.isnull().sum()

day            0
temperature    3
windspeed      3
event          4
dtype: int64

In [ ]:
whether_data

          day  temperature  windspeed   event
0  2017-01-01         32.0        6.0    Rain
1  2017-01-04          NaN        7.0   Sunny
2  2017-01-05         28.0        NaN    Snow
3  2017-01-06          NaN        7.0     NaN
4  2017-01-07         32.0        NaN    Rain
5  2017-01-08         31.0        2.0   Sunny
6  2017-01-09          NaN        NaN     NaN
7  2017-01-10         34.0        8.0  Cloudy
8  2017-01-11         40.0       12.0     NaN
9  2017-01-10         34.0        8.0  Cloudy
10 2017-01-11         40.0       12.0     NaN

In [ ]:
# Temporary changes
whether_data.fillna(45)

          day  temperature  windspeed   event
0  2017-01-01         32.0        6.0    Rain
1  2017-01-04         45.0        7.0   Sunny
2  2017-01-05         28.0       45.0    Snow
3  2017-01-06         45.0        7.0      45
4  2017-01-07         32.0       45.0    Rain
5  2017-01-08         31.0        2.0   Sunny
6  2017-01-09         45.0       45.0      45
7  2017-01-10         34.0        8.0  Cloudy
8  2017-01-11         40.0       12.0      45
9  2017-01-10         34.0        8.0  Cloudy
10 2017-01-11         40.0       12.0      45

In [ ]:
whether_data

          day  temperature  windspeed   event
0  2017-01-01         32.0        6.0    Rain
1  2017-01-04          NaN        7.0   Sunny
2  2017-01-05         28.0        NaN    Snow
3  2017-01-06          NaN        7.0     NaN
4  2017-01-07         32.0        NaN    Rain
5  2017-01-08         31.0        2.0   Sunny
6  2017-01-09          NaN        NaN     NaN
7  2017-01-10         34.0        8.0  Cloudy
8  2017-01-11         40.0       12.0     NaN
9  2017-01-10         34.0        8.0  Cloudy
10 2017-01-11         40.0       12.0     NaN

In [ ]:
whether_data["temperature"].mean()

np.float64(33.875)

In [ ]:
whether_data["temperature"].fillna(whether_data["temperature"].mean())

0     32.000
1     33.875
2     28.000
3     33.875
4     32.000
5     31.000
6     33.875
7     34.000
8     40.000
9     34.000
10    40.000
Name: temperature, dtype: float64

In [ ]:
whether_data["event"].mode()

0    Cloudy
1      Rain
2     Sunny
Name: event, dtype: object

In [ ]:
whether_data["event"].fillna(whether_data["event"].mode()[0])

0       Rain
1      Sunny
2       Snow
3     Cloudy
4       Rain
5      Sunny
6     Cloudy
7     Cloudy
8     Cloudy
9     Cloudy
10    Cloudy
Name: event, dtype: object

In [ ]:
# Temporay cahnges
# Drop every single column that contains nan values
whether_data.dropna()

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
5 2017-01-08         31.0        2.0   Sunny
7 2017-01-10         34.0        8.0  Cloudy
9 2017-01-10         34.0        8.0  Cloudy

In [ ]:
whether_data

          day  temperature  windspeed   event
0  2017-01-01         32.0        6.0    Rain
1  2017-01-04          NaN        7.0   Sunny
2  2017-01-05         28.0        NaN    Snow
3  2017-01-06          NaN        7.0     NaN
4  2017-01-07         32.0        NaN    Rain
5  2017-01-08         31.0        2.0   Sunny
6  2017-01-09          NaN        NaN     NaN
7  2017-01-10         34.0        8.0  Cloudy
8  2017-01-11         40.0       12.0     NaN
9  2017-01-10         34.0        8.0  Cloudy
10 2017-01-11         40.0       12.0     NaN

In [ ]:
whether_data.dropna(how="all")

          day  temperature  windspeed   event
0  2017-01-01         32.0        6.0    Rain
1  2017-01-04          NaN        7.0   Sunny
2  2017-01-05         28.0        NaN    Snow
3  2017-01-06          NaN        7.0     NaN
4  2017-01-07         32.0        NaN    Rain
5  2017-01-08         31.0        2.0   Sunny
6  2017-01-09          NaN        NaN     NaN
7  2017-01-10         34.0        8.0  Cloudy
8  2017-01-11         40.0       12.0     NaN
9  2017-01-10         34.0        8.0  Cloudy
10 2017-01-11         40.0       12.0     NaN

In [ ]:
whether_data.dropna(how="any")

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
5 2017-01-08         31.0        2.0   Sunny
7 2017-01-10         34.0        8.0  Cloudy
9 2017-01-10         34.0        8.0  Cloudy

In [ ]:
whether_data.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10     True
dtype: bool

In [ ]:
whether_data.duplicated().sum()

np.int64(2)

In [ ]:
whether_data.drop_duplicates()

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        7.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08         31.0        2.0   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0     NaN

In [ ]:
import pandas as pd

In [ ]:
whether_data=pd.read_excel("/content/whether_data.xls")

####sort values :

In [ ]:
whether_data.sort_values("temperature")

          day  temperature  windspeed   event
2  2017-01-05         28.0        NaN    Snow
5  2017-01-08         31.0        2.0   Sunny
0  2017-01-01         32.0        6.0    Rain
4  2017-01-07         32.0        NaN    Rain
7  2017-01-10         34.0        8.0  Cloudy
9  2017-01-10         34.0        8.0  Cloudy
8  2017-01-11         40.0       12.0     NaN
10 2017-01-11         40.0       12.0     NaN
1  2017-01-04          NaN        7.0   Sunny
3  2017-01-06          NaN        7.0     NaN
6  2017-01-09          NaN        NaN     NaN

In [ ]:
whether_data.sort_values("temperature",ascending=False)

          day  temperature  windspeed   event
10 2017-01-11         40.0       12.0     NaN
8  2017-01-11         40.0       12.0     NaN
9  2017-01-10         34.0        8.0  Cloudy
7  2017-01-10         34.0        8.0  Cloudy
4  2017-01-07         32.0        NaN    Rain
0  2017-01-01         32.0        6.0    Rain
5  2017-01-08         31.0        2.0   Sunny
2  2017-01-05         28.0        NaN    Snow
1  2017-01-04          NaN        7.0   Sunny
3  2017-01-06          NaN        7.0     NaN
6  2017-01-09          NaN        NaN     NaN

In [ ]:
whether_data.dtypes

day            datetime64[ns]
temperature           float64
windspeed             float64
event                  object
dtype: object

###inplace=True ==> parameters ==> permanent changes in dataframe

In [ ]:
whether_data["temperature"].fillna(whether_data["temperature"].mean(),inplace=True)

In [ ]:
whether_data

          day  temperature  windspeed   event
0  2017-01-01       32.000        6.0    Rain
1  2017-01-04       33.875        7.0   Sunny
2  2017-01-05       28.000        NaN    Snow
3  2017-01-06       33.875        7.0     NaN
4  2017-01-07       32.000        NaN    Rain
5  2017-01-08       31.000        2.0   Sunny
6  2017-01-09       33.875        NaN     NaN
7  2017-01-10       34.000        8.0  Cloudy
8  2017-01-11       40.000       12.0     NaN
9  2017-01-10       34.000        8.0  Cloudy
10 2017-01-11       40.000       12.0     NaN

###permanent Change the data type

In [ ]:
whether_data["temperature"]=whether_data["temperature"].astype("int64")

In [ ]:
whether_data

          day  temperature  windspeed   event
0  2017-01-01           32        6.0    Rain
1  2017-01-04           33        7.0   Sunny
2  2017-01-05           28        NaN    Snow
3  2017-01-06           33        7.0     NaN
4  2017-01-07           32        NaN    Rain
5  2017-01-08           31        2.0   Sunny
6  2017-01-09           33        NaN     NaN
7  2017-01-10           34        8.0  Cloudy
8  2017-01-11           40       12.0     NaN
9  2017-01-10           34        8.0  Cloudy
10 2017-01-11           40       12.0     NaN

In [ ]:
whether_data.dtypes

day            datetime64[ns]
temperature             int64
windspeed             float64
event                  object
dtype: object

###Check pandas Version

In [ ]:
import pandas as pd
print(pd.__version__)

2.2.2

###change column name

In [ ]:
whether_data.rename(columns={"day":"dates"},inplace=True)

In [ ]:
whether_data

        dates  temperature  windspeed   event
0  2017-01-01           32        6.0    Rain
1  2017-01-04           33        7.0   Sunny
2  2017-01-05           28        NaN    Snow
3  2017-01-06           33        7.0     NaN
4  2017-01-07           32        NaN    Rain
5  2017-01-08           31        2.0   Sunny
6  2017-01-09           33        NaN     NaN
7  2017-01-10           34        8.0  Cloudy
8  2017-01-11           40       12.0     NaN
9  2017-01-10           34        8.0  Cloudy
10 2017-01-11           40       12.0     NaN

###Replace particular data

In [ ]:
# Temperory change
whether_data.replace(7,"affan")

        dates  temperature windspeed   event
0  2017-01-01           32       6.0    Rain
1  2017-01-04           33     affan   Sunny
2  2017-01-05           28       NaN    Snow
3  2017-01-06           33     affan     NaN
4  2017-01-07           32       NaN    Rain
5  2017-01-08           31       2.0   Sunny
6  2017-01-09           33       NaN     NaN
7  2017-01-10           34       8.0  Cloudy
8  2017-01-11           40      12.0     NaN
9  2017-01-10           34       8.0  Cloudy
10 2017-01-11           40      12.0     NaN

In [ ]:
whether_data

        dates  temperature  windspeed   event
0  2017-01-01           32        6.0    Rain
1  2017-01-04           33        7.0   Sunny
2  2017-01-05           28        NaN    Snow
3  2017-01-06           33        7.0     NaN
4  2017-01-07           32        NaN    Rain
5  2017-01-08           31        2.0   Sunny
6  2017-01-09           33        NaN     NaN
7  2017-01-10           34        8.0  Cloudy
8  2017-01-11           40       12.0     NaN
9  2017-01-10           34        8.0  Cloudy
10 2017-01-11           40       12.0     NaN

In [ ]:
whether_data["windspeed"].replace(7,"vijay")

0       6.0
1     vijay
2       NaN
3     vijay
4       NaN
5       2.0
6       NaN
7       8.0
8      12.0
9       8.0
10     12.0
Name: windspeed, dtype: object

In [ ]:
whether_data

        dates  temperature  windspeed   event
0  2017-01-01           32        6.0    Rain
1  2017-01-04           33        7.0   Sunny
2  2017-01-05           28        NaN    Snow
3  2017-01-06           33        7.0     NaN
4  2017-01-07           32        NaN    Rain
5  2017-01-08           31        2.0   Sunny
6  2017-01-09           33        NaN     NaN
7  2017-01-10           34        8.0  Cloudy
8  2017-01-11           40       12.0     NaN
9  2017-01-10           34        8.0  Cloudy
10 2017-01-11           40       12.0     NaN

In [ ]:
# Permanent Change
whether_data["windspeed"].replace(7,"Affan",inplace=True)

/tmp/ipython-input-1116803303.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  whether_data["windspeed"].replace(7,"Affan",inplace=True)

In [ ]:
whether_data

        dates  temperature windspeed   event
0  2017-01-01           32       6.0    Rain
1  2017-01-04           33     Affan   Sunny
2  2017-01-05           28       NaN    Snow
3  2017-01-06           33     Affan     NaN
4  2017-01-07           32       NaN    Rain
5  2017-01-08           31       2.0   Sunny
6  2017-01-09           33       NaN     NaN
7  2017-01-10           34       8.0  Cloudy
8  2017-01-11           40      12.0     NaN
9  2017-01-10           34       8.0  Cloudy
10 2017-01-11           40      12.0     NaN

##Multiple Values/Missing Columns Value replace

In [ ]:
# multiple values
whether_data.replace([32,40,8,"Cloudy"],"Missing")

        dates temperature windspeed    event
0  2017-01-01     Missing       6.0     Rain
1  2017-01-04          33     Affan    Sunny
2  2017-01-05          28       NaN     Snow
3  2017-01-06          33     Affan      NaN
4  2017-01-07     Missing       NaN     Rain
5  2017-01-08          31       2.0    Sunny
6  2017-01-09          33       NaN      NaN
7  2017-01-10          34   Missing  Missing
8  2017-01-11     Missing      12.0      NaN
9  2017-01-10          34   Missing  Missing
10 2017-01-11     Missing      12.0      NaN

###Multiple Column Changes:

In [ ]:
# multiple columns ==> Dictionary
import numpy as np
whether_data.replace({"temperature":{33:5},"event":{np.nan:0}})

        dates  temperature windspeed   event
0  2017-01-01           32       6.0    Rain
1  2017-01-04            5     Affan   Sunny
2  2017-01-05           28       NaN    Snow
3  2017-01-06            5     Affan       0
4  2017-01-07           32       NaN    Rain
5  2017-01-08           31       2.0   Sunny
6  2017-01-09            5       NaN       0
7  2017-01-10           34       8.0  Cloudy
8  2017-01-11           40      12.0       0
9  2017-01-10           34       8.0  Cloudy
10 2017-01-11           40      12.0       0

In [ ]:
whether_data.fillna({"temperature":100,"windspeed":500,"event":1000})

        dates  temperature windspeed   event
0  2017-01-01           32       6.0    Rain
1  2017-01-04           33     Affan   Sunny
2  2017-01-05           28       500    Snow
3  2017-01-06           33     Affan    1000
4  2017-01-07           32       500    Rain
5  2017-01-08           31       2.0   Sunny
6  2017-01-09           33       500    1000
7  2017-01-10           34       8.0  Cloudy
8  2017-01-11           40      12.0    1000
9  2017-01-10           34       8.0  Cloudy
10 2017-01-11           40      12.0    1000

##fillna==parameter==> method="bfill" or "ffill" ==> backward fill and forward fill ==> used in time series data

- dates         - sales
- 12-1-2025     - 500
- 13-1-2025     - 1000
- 14-1-2025     - nan
- 15-1-2025     - 2000
- 16-1-2025     - 2500

In [ ]:
whether_data["windspeed"].fillna(method="ffill")

/tmp/ipython-input-274842947.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  whether_data["windspeed"].fillna(method="ffill")

0       6.0
1     Affan
2     Affan
3     Affan
4     Affan
5       2.0
6       2.0
7       8.0
8      12.0
9       8.0
10     12.0
Name: windspeed, dtype: object

In [ ]:
whether_data

        dates  temperature windspeed   event
0  2017-01-01           32       6.0    Rain
1  2017-01-04           33     Affan   Sunny
2  2017-01-05           28       NaN    Snow
3  2017-01-06           33     Affan     NaN
4  2017-01-07           32       NaN    Rain
5  2017-01-08           31       2.0   Sunny
6  2017-01-09           33       NaN     NaN
7  2017-01-10           34       8.0  Cloudy
8  2017-01-11           40      12.0     NaN
9  2017-01-10           34       8.0  Cloudy
10 2017-01-11           40      12.0     NaN

In [ ]:
whether_data["windspeed"].fillna(method="bfill")

/tmp/ipython-input-2630203982.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  whether_data["windspeed"].fillna(method="bfill")

0       6.0
1     Affan
2     Affan
3     Affan
4       2.0
5       2.0
6       8.0
7       8.0
8      12.0
9       8.0
10     12.0
Name: windspeed, dtype: object

###if Continue nan values present in a column

In [ ]:
import pandas as pd
whether_data2=pd.read_excel("/content/whether_data_limit.xls")
whether_data2

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        7.0   Sunny
2 2017-01-05          NaN        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08         31.0        2.0     NaN
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0     NaN

In [ ]:
whether_data2.fillna(method="bfill")

/tmp/ipython-input-3689401353.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  whether_data2.fillna(method="bfill")

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         32.0        7.0   Sunny
2 2017-01-05         32.0        7.0    Snow
3 2017-01-06         32.0        7.0    Rain
4 2017-01-07         32.0        2.0    Rain
5 2017-01-08         31.0        2.0  Cloudy
6 2017-01-09         34.0        8.0  Cloudy
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0     NaN

In [ ]:
whether_data2.fillna(method="bfill",limit=2)

/tmp/ipython-input-1273287432.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  whether_data2.fillna(method="bfill",limit=2)

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        7.0   Sunny
2 2017-01-05         32.0        7.0    Snow
3 2017-01-06         32.0        7.0    Rain
4 2017-01-07         32.0        2.0    Rain
5 2017-01-08         31.0        2.0  Cloudy
6 2017-01-09         34.0        8.0  Cloudy
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0     NaN

rank()

In [ ]:
whether_data2["rank"]=whether_data2["temperature"].rank()
whether_data2

         day  temperature  windspeed   event  rank
0 2017-01-01         32.0        6.0    Rain   2.5
1 2017-01-04          NaN        7.0   Sunny   NaN
2 2017-01-05          NaN        NaN    Snow   NaN
3 2017-01-06          NaN        7.0     NaN   NaN
4 2017-01-07         32.0        NaN    Rain   2.5
5 2017-01-08         31.0        2.0     NaN   1.0
6 2017-01-09          NaN        NaN     NaN   NaN
7 2017-01-10         34.0        8.0  Cloudy   4.0
8 2017-01-11         40.0       12.0     NaN   5.0